__ds_name = "CICMalMem2022"

__ds_size = None

__ds_paper_link = "https://www.unb.ca/cic/datasets/malmem-2022.html"

__ds_link = "https://drive.usercontent.google.com/download?id=1Lz07kYeIi1UXmwhHL6f52gPc8sbZxp2D&export=download&authuser=1&confirm=t&uuid=1c61797e-da84-478d-accb-81d313132bd6&at=APZUnTWwHcF_VwigcmUU76mMjrgN:1695918496913"

__csv_link = None

__fts_names = [
       'Category', 'pslist.nproc', 'pslist.nppid', 'pslist.avg_threads',
       'pslist.nprocs64bit', 'pslist.avg_handlers', 'dlllist.ndlls',
       'dlllist.avg_dlls_per_proc', 'handles.nhandles',
       'handles.avg_handles_per_proc', 'handles.nport', 'handles.nfile',
       'handles.nevent', 'handles.ndesktop', 'handles.nkey', 'handles.nthread',
       'handles.ndirectory', 'handles.nsemaphore', 'handles.ntimer',
       'handles.nsection', 'handles.nmutant', 'ldrmodules.not_in_load',
       'ldrmodules.not_in_init', 'ldrmodules.not_in_mem',
       'ldrmodules.not_in_load_avg', 'ldrmodules.not_in_init_avg',
       'ldrmodules.not_in_mem_avg', 'malfind.ninjections',
       'malfind.commitCharge', 'malfind.protection',
       'malfind.uniqueInjections', 'psxview.not_in_pslist',
       'psxview.not_in_eprocess_pool', 'psxview.not_in_ethread_pool',
       'psxview.not_in_pspcid_list', 'psxview.not_in_csrss_handles',
       'psxview.not_in_session', 'psxview.not_in_deskthrd',
       'psxview.not_in_pslist_false_avg',
       'psxview.not_in_eprocess_pool_false_avg',
       'psxview.not_in_ethread_pool_false_avg',
       'psxview.not_in_pspcid_list_false_avg',
       'psxview.not_in_csrss_handles_false_avg',
       'psxview.not_in_session_false_avg', 'psxview.not_in_deskthrd_false_avg',
       'modules.nmodules', 'svcscan.nservices', 'svcscan.kernel_drivers',
       'svcscan.fs_drivers', 'svcscan.process_services',
       'svcscan.shared_process_services',
       'svcscan.interactive_process_services', 'svcscan.nactive',
       'callbacks.ncallbacks', 'callbacks.nanonymous', 'callbacks.ngeneric',
       'Class'
    ]
__target_variable = "Category"
__real_cnt = {
        'Benign':                   29298,
        'Spyware-Transponder':      2410,
        'Spyware-Gator':            2200,
        'Ransomware-Shade':         2128,
        'Ransomware-Ako':           2000,
        'Spyware-180solutions':     2000,
        'Spyware-CWS':              2000,
        'Trojan-Refroso':           2000,
        'Trojan-Scar':              2000,
        'Ransomware-Conti':         1988,
        'Trojan-Emotet':            1967,
        'Ransomware-Maze':          1958,
        'Trojan-Zeus':              1950,
        'Ransomware-Pysa':          1717,
        'Trojan-Reconyc':           1570,
        'Spyware-TIBS':             1410
    }  # Actual number of samples in the csv file of each class
__label_map = {
    } # Map the actual label in the csv file with the label in the paper
__category_map = {
        'Benign':                   'Benign',
        'Trojan-Refroso':           'Malware',
        'Trojan-Scar':              'Malware',
        'Trojan-Reconyc':           'Malware',
        'Trojan-Zeus':              'Malware',
        'Trojan-Emotet':            'Malware',
        'Spyware-Transponder':      'Malware',
        'Spyware-TIBS':             'Malware',
        'Spyware-Gator':            'Malware',
        'Spyware-180solutions':     'Malware',
        'Spyware-CWS':              'Malware',
        'Ransomware-Shade':         'Malware',
        'Ransomware-Ako':           'Malware',
        'Ransomware-Conti':         'Malware',      
        'Ransomware-Maze':          'Malware',      
        'Ransomware-Pysa':          'Malware'
    } # Group the actual label in the csv file with the coresponding category in the paper
__binary_map = {
        'Benign':                   0,
        'Trojan-Refroso':           1,
        'Trojan-Scar':              1,
        'Trojan-Reconyc':           1,
        'Trojan-Zeus':              1,
        'Trojan-Emotet':            1,
        'Spyware-Transponder':      1,
        'Spyware-TIBS':             1,
        'Spyware-Gator':            1,
        'Spyware-180solutions':     1,
        'Spyware-CWS':              1,
        'Ransomware-Shade':         1,
        'Ransomware-Ako':           1,
        'Ransomware-Conti':         1,      
        'Ransomware-Maze':          1,      
        'Ransomware-Pysa':          1
    }
__label_true_name = [
        'Benign',
        'Trojan-Refroso',
        'Trojan-Scar',
        'Trojan-Reconyc',
        'Trojan-Zeus',
        'Trojan-Emotet',
        'Spyware-Transponder',
        'Spyware-TIBS',
        'Spyware-Gator',
        'Spyware-180solutions',
        'Spyware-CWS',
        'Ransomware-Shade',
        'Ransomware-Ako',
        'Ransomware-Conti',       
        'Ransomware-Maze',    
        'Ransomware-Pysa'
    ] # Map the actual label in the csv file with the label in the paper
__label_drop = [] # List the label be dropped
__label_cnt = {} # Actual number of samples loaded by function
__error_cnt = 0