#Info of the dataset
ds_name: ""
ds_size: None
ds_paper_link: ""
ds_link: ""
csv_link: None
fts_names: [ ]
target_variable: ""

# Actual number of samples in the csv file of each class
real_cnt: { }

# Map the actual label in the csv file with the label in the paper
label_map: { }

# Group the actual label in the csv file with the coresponding category in the paper
category_map: { }
binary_map: { }

# Map the actual label in the csv file with the label in the paper
label_true_name: [ ]

 # List the label be dropped
label_drop: [ ]
  