#Info of the dataset
ds_name: "CICIoT2023"
ds_size: None
ds_paper_link: "https://www.unb.ca/cic/datasets/iotdataset-2023.html"
ds_link: "https://drive.google.com/uc?export=download&id=1-0k47d_IAALSpj3tb2ROaTrBfaMz1R3o"
csv_link: None
fts_names: [ 
    "flow_duration", "Header_Length", "Protocol type", "Duration", "Rate", "Srate", "Drate", "fin_flag_number",
    "syn_flag_number", "rst_flag_number", "psh_flag_number", "ack_flag_number", "ece_flag_number", "cwr_flag_number",
    "ack_count", "syn_count", "fin_count", "urg_count", "rst_count", "HTTP", "HTTPS", "DNS", "Telnet", "SMTP",
    "SSH", "IRC", "TCP", "UDP", "DHCP", "ARP", "ICMP", "IPv", "LLC", "Tot sum", "Min", "Max", "AVG", "Std",
    "Tot size", "IAT", "Number", "Magnitue", "Radius", "Covariance", "Variance", "Weight", "label"
]
target_variable: "label"

# Actual number of samples in the csv file of each class
real_cnt: { 
    "BenignTraffic":            1098195,
    "DDoS-ACK_Fragmentation":   285104,
    "DDoS-UDP_Flood":           5412287,
    "DDoS-SlowLoris":           23426,
    "DDoS-ICMP_Flood":          7200504,
    "DDoS-RSTFINFlood":         4045285,
    "DDoS-PSHACK_Flood":        4094755,
    "DDoS-HTTP_Flood":          28790,
    "DDoS-UDP_Fragmentation":   286925,
    "DDoS-ICMP_Fragmentation":  452489,
    "DDoS-TCP_Flood":           4497667,
    "DDoS-SYN_Flood":           4059190,
    "DDoS-SynonymousIP_Flood":  3598138,
    "DictionaryBruteForce":     13064,
    "MITM-ArpSpoofing":         307593,
    "DNS_Spoofing":             178911,
    "DoS-TCP_Flood":            2671445,
    "DoS-HTTP_Flood":           71864,
    "DoS-SYN_Flood":            2028834,
    "DoS-UDP_Flood":            3318595,
    "Recon-PingSweep":          2262,
    "Recon-OSScan":             98259,
    "VulnerabilityScan":        37382,
    "Recon-PortScan":           82284,
    "Recon-HostDiscovery":      134378,
    "SqlInjection":             5245,
    "CommandInjection":         5409,
    "Backdoor_Malware":         3218,
    "Uploading_Attack":         1252,
    "XSS":                      3846,
    "BrowserHijacking":         5859,
    "Mirai-greip_flood":        751682,
    "Mirai-greeth_flood":       991866,
    "Mirai-udpplain":           890576
}

# Map the actual label in the csv file with the label in the paper
label_map: { }

# Group the actual label in the csv file with the coresponding category in the paper
category_map: {
    "BenignTraffic":            "Benign",
    "DDoS-ACK_Fragmentation":   "DoS",
    "DDoS-UDP_Flood":           "DoS",
    "DDoS-SlowLoris":           "DoS",
    "DDoS-ICMP_Flood":          "DoS",
    "DDoS-RSTFINFlood":         "DoS",
    "DDoS-PSHACK_Flood":        "DoS",
    "DDoS-HTTP_Flood":          "DoS",
    "DDoS-UDP_Fragmentation":   "DoS",
    "DDoS-ICMP_Fragmentation":  "DoS",
    "DDoS-TCP_Flood":           "DoS",
    "DDoS-SYN_Flood":           "DoS",
    "DDoS-SynonymousIP_Flood":  "DoS",
    "DictionaryBruteForce":     "BruteForce",
    "MITM-ArpSpoofing":         "Spoofing",
    "DNS_Spoofing":             "Spoofing",
    "DoS-TCP_Flood":            "DoS",
    "DoS-HTTP_Flood":           "DoS",
    "DoS-SYN_Flood":            "DoS",
    "DoS-UDP_Flood":            "DoS",
    "Recon-PingSweep":          "Recon",
    "Recon-OSScan":             "Recon",
    "VulnerabilityScan":        "Recon",
    "Recon-PortScan":           "Recon",
    "Recon-HostDiscovery":      "Recon",
    "SqlInjection":             "Web-based",
    "CommandInjection":         "Web-based",
    "Backdoor_Malware":         "Web-based",
    "Uploading_Attack":         "Web-based",
    "XSS":                      "Web-based",
    "BrowserHijacking":         "Web-based",
    "Mirai-greip_flood":        "Mirai",
    "Mirai-greeth_flood":       "Mirai",
    "Mirai-udpplain":           "Mirai"
}
binary_map: {
    "BenignTraffic":            "Benign",
    "DDoS-ACK_Fragmentation":   "Malicious",
    "DDoS-UDP_Flood":           "Malicious",
    "DDoS-SlowLoris":           "Malicious",
    "DDoS-ICMP_Flood":          "Malicious",
    "DDoS-RSTFINFlood":         "Malicious",
    "DDoS-PSHACK_Flood":        "Malicious",
    "DDoS-HTTP_Flood":          "Malicious",
    "DDoS-UDP_Fragmentation":   "Malicious",
    "DDoS-ICMP_Fragmentation":  "Malicious",
    "DDoS-TCP_Flood":           "Malicious",
    "DDoS-SYN_Flood":           "Malicious",
    "DDoS-SynonymousIP_Flood":  "Malicious",
    "DictionaryBruteForce":     "Malicious",
    "MITM-ArpSpoofing":         "Malicious",
    "DNS_Spoofing":             "Malicious",
    "DoS-TCP_Flood":            "Malicious",
    "DoS-HTTP_Flood":           "Malicious",
    "DoS-SYN_Flood":            "Malicious",
    "DoS-UDP_Flood":            "Malicious",
    "Recon-PingSweep":          "Malicious",
    "Recon-OSScan":             "Malicious",
    "VulnerabilityScan":        "Malicious",
    "Recon-PortScan":           "Malicious",
    "Recon-HostDiscovery":      "Malicious",
    "SqlInjection":             "Malicious",
    "CommandInjection":         "Malicious",
    "Backdoor_Malware":         "Malicious",
    "Uploading_Attack":         "Malicious",
    "XSS":                      "Malicious",
    "BrowserHijacking":         "Malicious",
    "Mirai-greip_flood":        "Malicious",
    "Mirai-greeth_flood":       "Malicious",
    "Mirai-udpplain":           "Malicious"
}

# Map the actual label in the csv file with the label in the paper
label_true_name: [
    "BenignTraffic", "DDoS-ACK_Fragmentation", "DDoS-UDP_Flood", "DDoS-SlowLoris", "DDoS-ICMP_Flood",
    "DDoS-RSTFINFlood", "DDoS-PSHACK_Flood", "DDoS-HTTP_Flood", "DDoS-UDP_Fragmentation", "DDoS-TCP_Flood",
    "DDoS-SYN_Flood", "DDoS-SynonymousIP_Flood", "DictionaryBruteForce", "MITM-ArpSpoofing", "DNS_Spoofing",
    "DoS-TCP_Flood", "DoS-HTTP_Flood", "DoS-SYN_Flood", "DoS-UDP_Flood", "Recon-PingSweep", "Recon-OSScan",
    "VulnerabilityScan", "Recon-PortScan", "Recon-HostDiscovery", "SqlInjection", "CommandInjection","Backdoor_Malware",
    "Uploading_Attack", "XSS", "BrowserHijacking", "Mirai-greip_flood", "Mirai-greeth_flood", "Mirai-udpplain"
]

 # List the label be dropped
label_drop: ["label"]
  