# Info of the dataset
ds_name: "CICDDoS2019"
ds_size: None
ds_paper_link: "https://www.unb.ca/cic/datasets/ddos-2019.html"
ds_link: "http://clouds.iec-uit.com/iec-iot-2021.idsdatasets/CICDDoS2019.zip"
csv_link: None
fts_names: [
    "Unnamed: 0", "Flow ID", " Source IP", " Source Port",
    " Destination IP", " Destination Port", " Protocol", " Timestamp",
    " Flow Duration", " Total Fwd Packets", " Total Backward Packets",
    "Total Length of Fwd Packets", " Total Length of Bwd Packets",
    " Fwd Packet Length Max", " Fwd Packet Length Min",
    " Fwd Packet Length Mean", " Fwd Packet Length Std",
    "Bwd Packet Length Max", " Bwd Packet Length Min",
    " Bwd Packet Length Mean", " Bwd Packet Length Std", "Flow Bytes/s",
    " Flow Packets/s", " Flow IAT Mean", " Flow IAT Std", " Flow IAT Max",
    " Flow IAT Min", "Fwd IAT Total", " Fwd IAT Mean", " Fwd IAT Std",
    " Fwd IAT Max", " Fwd IAT Min", "Bwd IAT Total", " Bwd IAT Mean",
    " Bwd IAT Std", " Bwd IAT Max", " Bwd IAT Min", "Fwd PSH Flags",
    " Bwd PSH Flags", " Fwd URG Flags", " Bwd URG Flags",
    " Fwd Header Length", " Bwd Header Length", "Fwd Packets/s",
    " Bwd Packets/s", " Min Packet Length", " Max Packet Length",
    " Packet Length Mean", " Packet Length Std", " Packet Length Variance",
    "FIN Flag Count", " SYN Flag Count", " RST Flag Count",
    " PSH Flag Count", " ACK Flag Count", " URG Flag Count",
    " CWE Flag Count", " ECE Flag Count", " Down/Up Ratio",
    " Average Packet Size", " Avg Fwd Segment Size",
    " Avg Bwd Segment Size", " Fwd Header Length.1", "Fwd Avg Bytes/Bulk",
    " Fwd Avg Packets/Bulk", " Fwd Avg Bulk Rate", " Bwd Avg Bytes/Bulk",
    " Bwd Avg Packets/Bulk", "Bwd Avg Bulk Rate", "Subflow Fwd Packets",
    " Subflow Fwd Bytes", " Subflow Bwd Packets", " Subflow Bwd Bytes",
    "Init_Win_bytes_forward", " Init_Win_bytes_backward",
    " act_data_pkt_fwd", " min_seg_size_forward", "Active Mean",
    " Active Std", " Active Max", " Active Min", "Idle Mean", " Idle Std",
    " Idle Max", " Idle Min", "SimillarHTTP", " Inbound", " Label"
]
target_variable: " Label"

# Actual number of samples in the csv file of each class
real_cnt: { 
    "TFTP": 20082580, "BENIGN": 113828, "DrDoS_LDAP": 2179930, "DrDoS_MSSQL": 4522492,
    "DrDoS_NetBIOS": 4093279, "DrDoS_SNMP": 5159870, "DrDoS_SSDP": 2610611, "DrDoS_UDP": 3134645,
    "UDP-lag": 366461, "WebDDoS": 439, "Syn": 6473789, "DrDoS_DNS": 5071011, "DrDoS_NTP": 1202642,
    "Portmap": 186960, "NetBIOS": 3657497, "LDAP": 1915122, "MSSQL": 5787453, "UDP": 3867155, "UDPLag": 1873
}

# Map the actual label in the csv file with the label in the paper
label_map: { 
    "DrDoS_LDAP"   :"LDAP",
    "DrDoS_NetBIOS":"NetBIOS",
    "DrDoS_MSSQL"  :"MSSQL",
    "DrDoS_SSDP"   :"SSDP",
    "DrDoS_UDP"    :"UDP",
    "DrDoS_DNS"    :"DNS",
    "DrDoS_SNMP"   :"SNMP",
    "DrDoS_NTP"    :"NTP",
    "UDP-lag"      :"UDPLag"
}

# Group the actual label in the csv file with the coresponding category in the paper
category_map: { 
    "BENIGN":   "Benign",
    "Syn":      "DoS",
    "UDP":      "DoS",
    "UDPLag":   "DoS",
    "MSSQL":    "DoS",
    "SSDP":     "DoS",
    "DNS":      "DoS",
    "LDAP":     "DoS",
    "NetBIOS":  "DoS",
    "Portmap":  "DoS",
    "SNMP":     "DoS",
    "NTP":      "DoS",
    "TFTP":     "DoS",
    "WebDDoS":  "DoS"
}
binary_map: { 
    "BENIGN":   "Benign",
    "Syn":      "Malicious",
    "UDP":      "Malicious",
    "UDPLag":   "Malicious",
    "MSSQL":    "Malicious",
    "SSDP":     "Malicious",
    "DNS":      "Malicious",
    "LDAP":     "Malicious",
    "NetBIOS":  "Malicious",
    "Portmap":  "Malicious",
    "SNMP":     "Malicious",
    "NTP":      "Malicious",
    "TFTP":     "Malicious",
    "WebDDoS":  "Malicious" 
}

# Map the actual label in the csv file with the label in the paper
label_true_name: [ 
    "BENIGN","Syn","UDP","UDPLag","MSSQL","SSDP","DNS",
    "LDAP","NetBIOS","Portmap","SNMP","NTP","TFTP","WebDDoS"
]

 # List the label be dropped
label_drop: [" Label"]
  