
ds_name : "CICMalMem2022"
ds_size : None
ds_paper_link : "https://www.unb.ca/cic/datasets/malmem-2022.html"
ds_link : "http://clouds.iec-uit.com/iec-iot-2021.idsdatasets/CICMalMem2022.zip"
csv_link : None

fts_names : [
       'Category', 'pslist.nproc', 'pslist.nppid', 'pslist.avg_threads',
       'pslist.nprocs64bit', 'pslist.avg_handlers', 'dlllist.ndlls',
       'dlllist.avg_dlls_per_proc', 'handles.nhandles',
       'handles.avg_handles_per_proc', 'handles.nport', 'handles.nfile',
       'handles.nevent', 'handles.ndesktop', 'handles.nkey', 'handles.nthread',
       'handles.ndirectory', 'handles.nsemaphore', 'handles.ntimer',
       'handles.nsection', 'handles.nmutant', 'ldrmodules.not_in_load',
       'ldrmodules.not_in_init', 'ldrmodules.not_in_mem',
       'ldrmodules.not_in_load_avg', 'ldrmodules.not_in_init_avg',
       'ldrmodules.not_in_mem_avg', 'malfind.ninjections',
       'malfind.commitCharge', 'malfind.protection',
       'malfind.uniqueInjections', 'psxview.not_in_pslist',
       'psxview.not_in_eprocess_pool', 'psxview.not_in_ethread_pool',
       'psxview.not_in_pspcid_list', 'psxview.not_in_csrss_handles',
       'psxview.not_in_session', 'psxview.not_in_deskthrd',
       'psxview.not_in_pslist_false_avg',
       'psxview.not_in_eprocess_pool_false_avg',
       'psxview.not_in_ethread_pool_false_avg',
       'psxview.not_in_pspcid_list_false_avg',
       'psxview.not_in_csrss_handles_false_avg',
       'psxview.not_in_session_false_avg', 'psxview.not_in_deskthrd_false_avg',
       'modules.nmodules', 'svcscan.nservices', 'svcscan.kernel_drivers',
       'svcscan.fs_drivers', 'svcscan.process_services',
       'svcscan.shared_process_services',
       'svcscan.interactive_process_services', 'svcscan.nactive',
       'callbacks.ncallbacks', 'callbacks.nanonymous', 'callbacks.ngeneric',
       'Class'
    ]
target_variable : "Category"
real_cnt : {
        'Benign':                   29298,
        'Spyware-Transponder':      2410,
        'Spyware-Gator':            2200,
        'Ransomware-Shade':         2128,
        'Ransomware-Ako':           2000,
        'Spyware-180solutions':     2000,
        'Spyware-CWS':              2000,
        'Trojan-Refroso':           2000,
        'Trojan-Scar':              2000,
        'Ransomware-Conti':         1988,
        'Trojan-Emotet':            1967,
        'Ransomware-Maze':          1958,
        'Trojan-Zeus':              1950,
        'Ransomware-Pysa':          1717,
        'Trojan-Reconyc':           1570,
        'Spyware-TIBS':             1410
    }  
label_map : {
    } 
category_map : {
        'Benign':                   'Benign',
        'Trojan-Refroso':           'Trojan',
        'Trojan-Scar':              'Trojan',
        'Trojan-Reconyc':           'Trojan',
        'Trojan-Zeus':              'Trojan',
        'Trojan-Emotet':            'Trojan',
        'Spyware-Transponder':      'Spyware',
        'Spyware-TIBS':             'Spyware',
        'Spyware-Gator':            'Spyware',
        'Spyware-180solutions':     'Spyware',
        'Spyware-CWS':              'Spyware',
        'Ransomware-Shade':         'Ransomware',
        'Ransomware-Ako':           'Ransomware',
        'Ransomware-Conti':         'Ransomware',      
        'Ransomware-Maze':          'Ransomware',      
        'Ransomware-Pysa':          'Ransomware'
    }
binary_map : {
        'Benign':                   'Benign',
        'Trojan-Refroso':           'Malicious',
        'Trojan-Scar':              'Malicious',
        'Trojan-Reconyc':           'Malicious',
        'Trojan-Zeus':              'Malicious',
        'Trojan-Emotet':            'Malicious',
        'Spyware-Transponder':      'Malicious',
        'Spyware-TIBS':             'Malicious',
        'Spyware-Gator':            'Malicious',
        'Spyware-180solutions':     'Malicious',
        'Spyware-CWS':              'Malicious',
        'Ransomware-Shade':         'Malicious',
        'Ransomware-Ako':           'Malicious',
        'Ransomware-Conti':         'Malicious',
        'Ransomware-Maze':          'Malicious',
        'Ransomware-Pysa':          'Malicious'
    }
label_true_name : [
        'Benign',
        'Trojan-Refroso',
        'Trojan-Scar',
        'Trojan-Reconyc',
        'Trojan-Zeus',
        'Trojan-Emotet',
        'Spyware-Transponder',
        'Spyware-TIBS',
        'Spyware-Gator',
        'Spyware-180solutions',
        'Spyware-CWS',
        'Ransomware-Shade',
        'Ransomware-Ako',
        'Ransomware-Conti',       
        'Ransomware-Maze',    
        'Ransomware-Pysa'
    ]
label_drop : ["Category"] 